# These are supported funding model platforms

github: [opennexora]
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
polar:
buy_me_a_coffee:
custom: ["https://nexora.dev/donate"]
